# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubeSwitcher < Formula
  desc "A simple tool to switch between Kubernetes contexts."
  homepage "https://github.com/mirceanton/kubectl-switch"
  version "2.0.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/mirceanton/kubectl-switch/releases/download/v2.0.0/kubectl-switch_darwin_amd64.tar.gz"
      sha256 "31fa6e087f6c88f384220697a7117c9aa2c7b2d787231812b804405fa5c18b76"

      def install
        bin.install "kubectl-switch"
      end
    end
    on_arm do
      url "https://github.com/mirceanton/kubectl-switch/releases/download/v2.0.0/kubectl-switch_darwin_arm64.tar.gz"
      sha256 "b78deb8ae617e8debfa29101c2670439a76ce584c3cf91576ab6d36cf0ec9884"

      def install
        bin.install "kubectl-switch"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mirceanton/kubectl-switch/releases/download/v2.0.0/kubectl-switch_linux_amd64.tar.gz"
        sha256 "6dbab55bdbe7483b61e946cd4f01ad45653966678bfc26162d5c2bb6f1f22213"

        def install
          bin.install "kubectl-switch"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mirceanton/kubectl-switch/releases/download/v2.0.0/kubectl-switch_linux_arm64.tar.gz"
        sha256 "1ea3c80be186bc3b651158b29f62a97612ce5f749c3d885c03fe852ac2fbc611"

        def install
          bin.install "kubectl-switch"
        end
      end
    end
  end

  test do
    system "#{bin}/kubectl-switch", "--help"
  end
end
