# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlSwitch < Formula
  desc "A simple tool to switch between Kubernetes contexts."
  homepage "https://github.com/mirceanton/kubectl-switch"
  version "2.4.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirceanton/kubectl-switch/releases/download/v2.4.8/kubectl-switch_darwin_amd64.tar.gz"
      sha256 "1ae44ba9d19b359c01c19dcac538097c6628bbf085e6690ea9508e18099c9846"

      define_method(:install) do
        bin.install "kubectl-switch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirceanton/kubectl-switch/releases/download/v2.4.8/kubectl-switch_darwin_arm64.tar.gz"
      sha256 "574df78dbe3e26abfa534f3754204b8ce5ee2a6e271c4b79b8b8398975741e27"

      define_method(:install) do
        bin.install "kubectl-switch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirceanton/kubectl-switch/releases/download/v2.4.8/kubectl-switch_linux_amd64.tar.gz"
      sha256 "881136a434246a234a6ee92a28e44fcb6212d64bd9f2a50b3fae9c5981e42eee"
      define_method(:install) do
        bin.install "kubectl-switch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirceanton/kubectl-switch/releases/download/v2.4.8/kubectl-switch_linux_arm64.tar.gz"
      sha256 "1530691fcd7f399318c13479cf7d384eacd91c755f1a48202477967a28d684f8"
      define_method(:install) do
        bin.install "kubectl-switch"
      end
    end
  end

  test do
    system "#{bin}/kubectl-switch", "--help"
  end
end
