# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Talstomize < Formula
  desc "Like kustomize, but for Talos!"
  homepage "https://github.com/mirceanton/talstomize"
  version "0.1.0-rc.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirceanton/talstomize/releases/download/v0.1.0-rc.1/talstomize_darwin_amd64.tar.gz"
      sha256 "874d7c1e4b6209d285667edbbc948ac4cae8de4784a3666bdaab84452aaf6866"

      define_method(:install) do
        bin.install "talstomize"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirceanton/talstomize/releases/download/v0.1.0-rc.1/talstomize_darwin_arm64.tar.gz"
      sha256 "4e6cf73c0d34e9dcb3e0c1bdb29e146c283b1ce6c8a72df1371c9a8f5146ef07"

      define_method(:install) do
        bin.install "talstomize"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirceanton/talstomize/releases/download/v0.1.0-rc.1/talstomize_linux_amd64.tar.gz"
      sha256 "8e6186e927322c16a249fd62ee13fbbdda9d9e484b39e26b29857157bc6e7250"
      define_method(:install) do
        bin.install "talstomize"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirceanton/talstomize/releases/download/v0.1.0-rc.1/talstomize_linux_arm64.tar.gz"
      sha256 "f6b1ee8328b20861417db0cfe74f33ece162f7f8286b8f0541fa710c69ebcc9d"
      define_method(:install) do
        bin.install "talstomize"
      end
    end
  end

  test do
    system "#{bin}/talstomize", "--help"
  end
end
