# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Talswitcher < Formula
  desc "A simple tool to help manage multiple talosconfig files."
  homepage "https://github.com/mirceanton/talswitcher"
  version "2.2.20"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirceanton/talswitcher/releases/download/v2.2.20/talswitcher_darwin_amd64.tar.gz"
      sha256 "4eeab4dd514b9ce6484e07b10033df4f95b880bcd5002986d8b80211cca99bdc"

      define_method(:install) do
        bin.install "talswitcher"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirceanton/talswitcher/releases/download/v2.2.20/talswitcher_darwin_arm64.tar.gz"
      sha256 "e6eb96d53a08e7d054b4b95b6330c67b8891164d228358eca58f37e66eecfeeb"

      define_method(:install) do
        bin.install "talswitcher"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirceanton/talswitcher/releases/download/v2.2.20/talswitcher_linux_amd64.tar.gz"
      sha256 "b83061920d1e2b41bd02bbb7cca7bc43b359253fb8fd0d9d0ee2f972b0acd17c"
      define_method(:install) do
        bin.install "talswitcher"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirceanton/talswitcher/releases/download/v2.2.20/talswitcher_linux_arm64.tar.gz"
      sha256 "52c1774060383012f7ea6132586739aed1710f3d449344ca09eb20d98904aa13"
      define_method(:install) do
        bin.install "talswitcher"
      end
    end
  end

  test do
    system "#{bin}/talswitcher", "--help"
  end
end
