# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tesmartctl < Formula
  desc "A CLI for controlling TeSmart KVM switches."
  homepage "https://github.com/mirceanton/tesmartctl"
  version "1.0.1"
  license "GPLv3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirceanton/tesmartctl/releases/download/v1.0.1/tesmartctl_darwin_amd64.tar.gz"
      sha256 "f25c9297d6b64ec5c33132f156a588b1b12ee2c4da2ec03732a2cf7eec8700a2"

      def install
        bin.install "tesmartctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirceanton/tesmartctl/releases/download/v1.0.1/tesmartctl_darwin_arm64.tar.gz"
      sha256 "1904ac3cda8243b29a61796113e4e1ba0a4d5c792cdfe8f4c382b7f16a2ddf8a"

      def install
        bin.install "tesmartctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/mirceanton/tesmartctl/releases/download/v1.0.1/tesmartctl_linux_amd64.tar.gz"
      sha256 "f2fb420a5cd05c23ac317de77bfce6d5410b963ccff078c721468e754bc8f544"
      def install
        bin.install "tesmartctl"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/mirceanton/tesmartctl/releases/download/v1.0.1/tesmartctl_linux_arm64.tar.gz"
      sha256 "09e3682f6275c970ae50e38be3ce1dbc6c8e2c58ec03ee37fe0470cf122d578b"
      def install
        bin.install "tesmartctl"
      end
    end
  end

  test do
    system "#{bin}/tesmartctl", "--help"
  end
end
