# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tesmartctl < Formula
  desc "A CLI for controlling TeSmart KVM switches."
  homepage "https://github.com/mirceanton/tesmartctl"
  version "1.0.2"
  license "GPLv3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirceanton/tesmartctl/releases/download/v1.0.2/tesmartctl_darwin_amd64.tar.gz"
      sha256 "17525e3b1f720e237a1c7d82df8bc0f4e0c152799b88d5bc8f19cf6abfb0e9e2"

      def install
        bin.install "tesmartctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirceanton/tesmartctl/releases/download/v1.0.2/tesmartctl_darwin_arm64.tar.gz"
      sha256 "8929335e26afac5b0f7bdb056aee9c8bdbb94278065fc93b3d7d76e46c1812b3"

      def install
        bin.install "tesmartctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirceanton/tesmartctl/releases/download/v1.0.2/tesmartctl_linux_amd64.tar.gz"
      sha256 "1716cf9364a04c33eb6533c16c0e4a750a8dd09fc16ff7301bc5db72a9889728"
      def install
        bin.install "tesmartctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirceanton/tesmartctl/releases/download/v1.0.2/tesmartctl_linux_arm64.tar.gz"
      sha256 "78d5338144819cca5d070c8f34edd8cb034e109f60f223a63589c9ebd3282b3d"
      def install
        bin.install "tesmartctl"
      end
    end
  end

  test do
    system "#{bin}/tesmartctl", "--help"
  end
end
