# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tesmartctl < Formula
  desc "A CLI for controlling TeSmart KVM switches."
  homepage "https://github.com/mirceanton/tesmartctl"
  version "1.0.4"
  license "GPLv3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirceanton/tesmartctl/releases/download/v1.0.4/tesmartctl_darwin_amd64.tar.gz"
      sha256 "a324980b0db43753524ab5410a9b3de5be44d71ef4363fa68c8e593d3ba40a9e"

      def install
        bin.install "tesmartctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirceanton/tesmartctl/releases/download/v1.0.4/tesmartctl_darwin_arm64.tar.gz"
      sha256 "7eed49be6b0bf2a9624a918b6bf36781629725c37e42c6cafa47e52c60243b42"

      def install
        bin.install "tesmartctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirceanton/tesmartctl/releases/download/v1.0.4/tesmartctl_linux_amd64.tar.gz"
      sha256 "f48301d5f66f132facb54815c14985dade762ef405cf9cfeb121c5febbe4d4c6"
      def install
        bin.install "tesmartctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirceanton/tesmartctl/releases/download/v1.0.4/tesmartctl_linux_arm64.tar.gz"
      sha256 "b129a500d9e0b0bc18a0c6dd807baa7fc92094648f81f61a5097436f1897786f"
      def install
        bin.install "tesmartctl"
      end
    end
  end

  test do
    system "#{bin}/tesmartctl", "--help"
  end
end
